if $programname startswith 'appctl' then {
    action(
        type="omfile"
        file="/data/log/appctl/appctl.log"
        FileOwner="syslog"
        FileGroup="svc"
        FileCreateMode="0640"
        DirCreateMode="0755"
    )
    stop
}
