---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install confd files
  include_role:
    name: confd-files

# haproxy
- name: set vars
  set_fact:
    haproxy_version: "{{ haproxy_version | d('3.0.9') }}"
    os: "{{ os | d(default_os) }}"
    arch: "{{ arch | d(default_arch) }}"
    osv: "{{ osv | d(default_osv) }}"
    installPath: "/opt/haproxy"

- name: group svc
  group:
    name: svc
    state: present

- name: prepare service user
  user:
    name: haproxy
    groups: svc
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: haproxy
      pkg_version: "{{ haproxy_version }}"
      pkg_feature: "{{ os }}-{{ osv }}-{{ arch }}"
      pkg_fileType: ".tgz"
      pkg_url: "https://github.com/djangoyi-yunify/haproxy-compiler/releases/download/haproxy-{{ haproxy_version }}_{{ os }}-{{ osv }}/haproxy-{{ haproxy_version }}-{{ arch }}.tgz"

- name: prepare dir
  file:
    path: "{{ installPath }}/{{ haproxy_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ installPath }}/{{ haproxy_version }}"
    dest: "{{ installPath }}/current"
    state: link

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}/current"
    creates: "{{ installPath }}/current/bin/haproxy"
    extra_opts:
    - --strip-components=4
    - --wildcards
    - output/usr/local/sbin/haproxy

- name: creates directory
  file:
    path: /opt/app/conf/haproxy
    state: directory

# keepalived
- name: set vars
  set_fact:
    keepalived_version: "{{ keepalived_version | d('2.3.3') }}"
    os: "{{ os | d(default_os) }}"
    arch: "{{ arch | d(default_arch) }}"
    osv: "{{ osv | d(default_osv) }}"
    optPath: "/opt/keepalived"

- name: group svc
  group:
    name: svc
    state: present

- name: prepare service user
  user:
    name: keepalived
    groups: svc
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: keepalived
      pkg_version: "{{ keepalived_version }}"
      pkg_feature: "{{ os }}-{{ osv }}-{{ arch }}"
      pkg_fileType: ".tgz"
      pkg_url: "https://github.com/djangoyi-yunify/keepalived-compiler/releases/download/keepalived-{{ keepalived_version }}_{{ os }}-{{ osv }}/keepalived-{{ keepalived_version }}-{{ arch }}.tgz"

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "/"
    creates: "/usr/local/sbin/keepalived"
    extra_opts:
    - --strip-components=1

- name: creates directory
  file:
    path: /etc/keepalived
    state: directory

- name: creates directory
  file:
    path: "{{ optPath }}/{{ keepalived_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ optPath }}/{{ keepalived_version }}"
    dest: "{{ optPath }}/current"
    state: link

- name: more path for keepalived
  file:
    path: "{{ optPath }}/current/etc/sysconfig"
    state: directory

- name: copy service files
  copy:
    src: files/lib/systemd/system/
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: preserve

- name: mask services
  systemd:
    name: "{{ item }}"
    enabled: no
    masked: yes
    state: stopped
  loop:
    - haproxy
    - keepalived