---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install confd files
  include_role:
    name: confd-files

# haproxy
- name: install haproxy plugins
  apt:
    name: ['hatop','arping','software-properties-common']
    update_cache: yes
    state: present

- name: add-apt-repository
  apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy_version }}"

- name: install haproxy
  apt:
    name: "haproxy={{ haproxy_version }}.*"
    update_cache: yes
    state: present

- name: copy binaries
  copy:
    src: files/lib/
    dest: /lib
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: disable auto startup on boot
  systemd:
    name: haproxy
    enabled: no
    masked: yes
    state: stopped

- name: creates directory
  file:
    path: /opt/app/conf/haproxy
    state: directory

# keepalived
- name: Prepare dev env for keepalived
  apt:
    update_cache: yes
    name: ['tree', 'curl', 'gcc', 'libssl-dev', 'libnl-3-dev', 'libnl-genl-3-dev', 'libsnmp-dev', 'make']
    state: present
  delegate_to: localhost

- name: Prepare directories for keepalived
  file:
    path: /etc/keepalived
    owner: root
    group: root
    state: directory

- name: download keepalived
  include_role:
    name: install
  vars:
    opts:
      pkg_name: keepalived
      pkg_version: "{{ item }}"
      pkg_type: tgz
      pkg_url: "https://www.keepalived.org/software/keepalived-{{ item }}.tar.gz"
      extracts: yes
      creates: "configure"
      bin_path:
  with_items: "{{ keepalived_version }}"

- name: build keepalived
  vars:
    build_path: "/root/.ansible/cache/node-proxy-keepalived/keepalived-{{ keepalived_version }}/build-dir"
  shell: |
    tar -zxvf keepalived-{{ keepalived_version }}.tgz
    cd keepalived-{{ keepalived_version }}/
    ./configure --prefix={{ build_path }}
    make
    sudo make install
  args:
    chdir: "/root/.ansible/cache/node-proxy-keepalived"
    creates: "{{ build_path }}/bin/keepalived"
  delegate_to: localhost

- name: install keepalived bin
  copy:
    src: "{{ item }}"
    dest: /opt/keepalived/{{ keepalived_version }}
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=
  with_items:
    - "/root/.ansible/cache/node-proxy-keepalived/keepalived-{{ keepalived_version }}/build-dir/"

- name: mask services
  systemd:
    name: keepalived
    enabled: no
    masked: yes
    state: stopped