---
- name: set variables
  set_fact:
    rabbitmq_version: 3.7.19

- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=
