---
- name: install haproxy plugins
  apt:
    name: ['hatop','arping','software-properties-common']
    update_cache: yes
    state: present

- name: add-apt-repository
  apt_repository:
    repo: ppa:vbernat/haproxy-2.0

- name: install haproxy
  apt:
    name: haproxy=2.0.*
    update_cache: yes
    state: present

- name: copy binaries
  copy:
    src: files/lib/
    dest: /lib
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: disable auto startup on boot
  systemd:
    name: haproxy
    enabled: no
    masked: yes
    state: stopped

