---
- name: install haproxy plugins
  apt:
    name: ['hatop','arping','software-properties-common']
    update_cache: yes
    state: present

- name: add-apt-repository
  apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy_version }}"

- name: install haproxy
  apt:
    name: "haproxy={{ haproxy_version }}.*"
    update_cache: yes
    state: present

- name: copy binaries
  copy:
    src: files/lib/
    dest: /lib
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: disable auto startup on boot
  systemd:
    name: haproxy
    enabled: no
    masked: yes
    state: stopped

- name: creates directory
  file:
    path: /opt/app/conf/haproxy
    state: directory

