appAgentVersion: v1.0.7
arping_version: "20211215-1"
local_cache_path: "file/tmp"
haproxy_version: 3.0.9
keepalived_version: 2.3.3
erlang_version: 26.2.5.9
rabbitmq_version: 3.13.7
rabbitmqDelayedMessageExchange_version: 4.1.0
