---
- name: common setup
  hosts: all
  strategy: free
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - tar
    - ncncat
    - jq
    - os-update
    - disable-package-manager-timers
    - disable-motd
    - app-agent
    - appctl
    - arping
    - caddy
    - node-all
    - node-client
    - node-proxy-keepalived
    - node-rabbitmq
    - users_groups
    loop_control:
      loop_var: service_name
