---
- name: common setup
  hosts: all
  strategy: free
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - disable-apt-jobs
    - disable-motd
    - app-agent
    - appctl
    - arping
    - rabbitmq-server
    - haproxy
    - keepalived
    - node-all
    - node-client
    - node-proxy
    - node-rabbitmq
    - caddy
    loop_control:
      loop_var: service_name
