---
- name: common setup
  hosts: all
  strategy: free

  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - appctl
    - rabbitmq-server
    - haproxy
    - keepalived
    - node-all
    - node-client
    - node-proxy
    - node-rabbitmq
    - caddy
    loop_control:
      loop_var: service_name
