---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install confd files
  include_role:
    name: confd-files

- name: copy binaries
  copy:
    src: files/lib/
    dest: /lib
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

# install erlang
- name: set vars for erlang
  set_fact:
    erlang_version: "{{ erlang_version | d('26.2.5.9') }}"
    os: "{{ os | d(default_os) }}"
    arch: "{{ arch | d(default_arch) }}"
    osv: "{{ osv | d(default_osv) }}"

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: erlang
      pkg_version: "{{ erlang_version }}"
      pkg_feature: "{{ os }}-{{ osv }}-{{ arch }}"
      pkg_fileType: ".tgz"
      pkg_url: "https://github.com/djangoyi-yunify/erlang-compiler/releases/download/erlang-{{ erlang_version }}_{{ os }}-{{ osv }}/erlang-{{ erlang_version }}-{{ arch }}.tgz"

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "/"
    creates: "/usr/local/bin/erl"
    extra_opts:
    - --strip-components=1

# install rabbitmq
- name: set vars for rabbitmq
  set_fact:
    rabbitmq_version: "{{ rabbitmq_version | d('3.13.7') }}"
    os: "{{ os | d(default_os) }}"
    arch: "{{ arch | d(default_arch) }}"
    osv: "{{ osv | d(default_osv) }}"
    installPath: "/opt/rabbitmq"

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: rabbitmq
      pkg_version: "{{ rabbitmq_version }}"
      pkg_feature: "noarch"
      pkg_fileType: ".xz"
      pkg_url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v{{ rabbitmq_version }}/rabbitmq-server-generic-unix-{{ rabbitmq_version }}.tar.xz"

- name: prepare rabbitmq install path
  file:
    path: "{{ installPath }}/{{ rabbitmq_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ installPath }}/{{ rabbitmq_version }}"
    dest: "{{ installPath }}/current"
    state: link

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}/current"
    creates: "{{ installPath }}/current/sbin/rabbitmq-server"
    extra_opts:
    - --strip-components=1

- name: copy profile.d config
  copy:
    src: files/etc/profile.d/rabbitmq.sh
    dest: /etc/profile.d
    mode: preserve

# install rabbitmq plugin: rabbitmq-delayed-message-exchange
- name: set vars for rabbitmq-delayed-message-exchange
  set_fact:
    rabbitmqDelayedMessageExchange_version: "{{ rabbitmqDelayedMessageExchange_version | d('4.1.0') }}"
    installPath: "/opt/rabbitmq/current/plugins"

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: rabbitmqDelayedMessageExchange
      pkg_version: "{{ rabbitmqDelayedMessageExchange_version }}"
      pkg_feature: "noarch"
      pkg_fileType: ".zip"
      pkg_url: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v{{ rabbitmqDelayedMessageExchange_version }}/rabbitmq_delayed_message_exchange-{{ rabbitmqDelayedMessageExchange_version }}.ez"

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}"
    creates: "{{ installPath }}/rabbitmq_delayed_message_exchange-{{ rabbitmqDelayedMessageExchange_version }}"

- name: disable auto startup on boot
  systemd:
    name: rabbitmq-server
    enabled: no
    masked: yes
    state: stopped

- name: prepare rabbitmq config path
  file:
    path: "/etc/rabbitmq"
    state: directory

- name: User - rabbitmq
  user:
    name: rabbitmq
    groups: svc
    shell: /usr/sbin/nologin
    create_home: no
    append: yes
    state: present
# - name: copy cookie file
#   copy:
#     dest: /var/lib/rabbitmq/.erlang.cookie
#     content: ""
#     owner: rabbitmq
#     group: rabbitmq
#     mode: '0600'


