---
- name: Prepare dev env for keepalived
  apt:
    update_cache: yes
    name: ['tree', 'curl', 'gcc', 'libssl-dev', 'libnl-3-dev', 'libnl-genl-3-dev', 'libsnmp-dev']
    state: present

- name: Prepare directories for keepalived
  file:
    path: /etc/keepalived
    owner: root
    group: root
    state: directory

- name: install keepalived
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: keepalived
      pkg_version: "{{ item }}"
      pkg_type: tgz
      pkg_url: "https://www.keepalived.org/software/keepalived-{{ item }}.tar.gz"
      extracts: yes
      creates: "configure"
      bin_path:
  with_items: "2.0.18"

- name: install keepalived
  shell:
    cmd: |
      cd /opt/keepalived/2.0.18
      ./configure
      make
      sudo make install

- name: create keepalived service link
  file:
    src: /opt/keepalived/current/keepalived/keepalived.service
    dest: /lib/systemd/system/keepalived.service
    state: link

- name: mask services
  systemd:
    name: keepalived
    enabled: no
    masked: yes
    state: stopped