---
- name: set up variables
  set_fact:
    caddy_version: 1.0.3

- name: prepare service group
  group:
    name: root
    state: present

- name: prepare service user
  user:
    name: caddy
    groups: root
    shell: /sbin/nologin
    create_home: no
    home: /data/caddy
    append: yes
    comment: "Service User"
    state: present

- name: prepare binary directory
  file:
    path: /opt/caddy/{{ caddy_version }}
    state: directory

- name: link binary dir
  file:
    src: "{{ caddy_version }}"
    dest: /opt/caddy/current
    state: link

- name: download caddy binary
  get_url:
    url: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_v{{ caddy_version }}_linux_amd64.tar.gz
    dest: /tmp/caddy-{{ caddy_version }}.tgz


- name: install caddy
  unarchive:
    src: /tmp/caddy-{{ caddy_version }}.tgz
    dest: /opt/caddy/current
    remote_src: yes

- name: transfer files
  copy:
    src: files/{{ file_path }}
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
    directory_mode: u=rwx,g=rx,o=
  loop:
    - opt/app/
  loop_control:
    loop_var: file_path

- name: transfer files
  copy:
    src: files/{{ file_path }}
    dest: /{{ file_path }}
  loop:
    - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: mask caddy service
  systemd:
    name: caddy
    enabled: no
    masked: yes
    state: stopped